spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/coin_notice?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
